# Description:
#   MorphNet: Deep Network Structure Learning.

load("//tools/build_defs/license:license.bzl", "license")

package(
    default_applicable_licenses = ["//third_party/py/morph_net:license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    package_name = "morph_net",
)

licenses(["notice"])

exports_files(["LICENSE"])
